version: "3.8"
services:
  postgres:
    image: postgres:latest
    env_file:
      - python_django_resume_project/docker.env
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - "./veritabani.sql:/veritabani.sql"
    command: -p 5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
        - postgres
    env_file:
      - python_django_resume_project/docker.env
    volumes:
      - .:/srv/app #continuous development
    ports:
      - "0.0.0.0:8000:8000"
    command: gunicorn python_django_resume_project.wsgi:application --bind 0.0.0.0:8000
volumes:
  static-data:
  postgres-data:
