# Generated by Django 4.1.5 on 2024-02-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Name of the setting', max_length=254, verbose_name='Setting Name')),
                ('description', models.CharField(blank=True, default='', help_text='Description of the setting', max_length=254, verbose_name='Description')),
                ('image', models.ImageField(blank=True, help_text='Image of the setting', upload_to='images/', verbose_name='Image')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Date when the record was last updated', verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Date when the record was created', verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Image Setting',
                'verbose_name_plural': 'Image Settings',
                'ordering': ('name', 'description'),
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
