# Generated by Django 4.1.5 on 2024-02-28 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_imagesetting_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Date when the record was last updated', verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Date when the record was created', verbose_name='Created Date')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the skill', verbose_name='Order')),
                ('name', models.CharField(blank=True, default='', help_text='Name of the skill', max_length=254, verbose_name='Skill Name')),
                ('percentage', models.PositiveIntegerField(default=50, help_text='Percentage of the skill', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ('name', 'percentage'),
            },
        ),
    ]
