# Generated by Django 4.1.5 on 2024-02-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_experience_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Date when the record was last updated', verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Date when the record was created', verbose_name='Created Date')),
                ('school_name', models.CharField(blank=True, default='', help_text='Name of the school', max_length=254, verbose_name='School Name')),
                ('major', models.CharField(blank=True, default='', help_text='Major in the school', max_length=254, verbose_name='Major')),
                ('department', models.CharField(blank=True, default='', help_text='Department in the school', max_length=254, verbose_name='Department')),
                ('start_date', models.DateField(blank=True, help_text='Start date of the education', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='End date of the education', null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ('start_date',),
            },
        ),
    ]
