# Generated by Django 4.1.5 on 2024-02-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_education_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Date when the record was last updated', verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Date when the record was created', verbose_name='Created Date')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the social link', verbose_name='Order')),
                ('name', models.CharField(blank=True, default='', help_text='Name of the social link', max_length=254, verbose_name='Name')),
                ('link', models.URLField(blank=True, default='', help_text='Link of the social link', max_length=254, verbose_name='Link')),
                ('icon', models.CharField(blank=True, default='', help_text='Icon of the social link', max_length=254, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ('order',),
            },
        ),
    ]
