# Generated by Django 4.1.5 on 2024-04-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Date when the record was last updated', verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Date when the record was created', verbose_name='Created Date')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the document', verbose_name='Order')),
                ('slug', models.SlugField(blank=True, default='', max_length=254, verbose_name='Slug')),
                ('file', models.FileField(blank=True, upload_to='documents/', verbose_name='File')),
                ('button_text', models.CharField(blank=True, default='', max_length=254, verbose_name='Button Text')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ('order',),
            },
        ),
    ]
